directory: '/Volumes/STORE/tagged_music/'
library: ~/Music/music_library.blb
plugins: copyartifacts
import:
  copy: yes
  resume: ask
  log: ~/Music/beets/beets.log
  duplicate_action: skip
  incremental: yes
paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title
ignore: ._* *~ .DS_Store
ignore_hidden: yes
match:
  strong_rec_thresh: 0.05
per_disc_numbering: yes
ui:
  color: yes
